apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  config.xml: |
    <clickhouse>
        <logger>
            <level>debug</level>
            <console>true</console>
            <log remove="remove"/>
            <errorlog remove="remove"/>
        </logger>
        
        <query_log>
            <database>system</database>
            <table>query_log</table>
        </query_log>
        
        <listen_host>0.0.0.0</listen_host>
        <http_port>8123</http_port>
        <tcp_port>9000</tcp_port>
        <interserver_http_host>clickhouse-0.clickhouse.default.svc.cluster.local</interserver_http_host>

        <interserver_http_port>9009</interserver_http_port>
        
        <max_connections>4096</max_connections>
        <keep_alive_timeout>3</keep_alive_timeout>
        <max_concurrent_queries>100</max_concurrent_queries>
        <uncompressed_cache_size>8589934592</uncompressed_cache_size>
        <mark_cache_size>5368709120</mark_cache_size>
        
        <path>/var/lib/clickhouse/</path>
        <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
        <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
        
        <users_config>users.xml</users_config>
        <default_profile>default</default_profile>
        <default_database>default</default_database>
        <timezone>Europe/Moscow</timezone>
        <mlock_executable>false</mlock_executable>
        
        <remote_servers>
            <company_cluster>
                <shard>
                    <replica>
                        <default_database>shard</default_database>
                        <host>clickhouse-0.clickhouse.default.svc.cluster.local</host>
                        <port>9000</port>
                    </replica>
                    <replica>
                        <default_database>replica</default_database>
                        <host>clickhouse-1.clickhouse.default.svc.cluster.local</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </company_cluster>
        </remote_servers>

        <zookeeper>
            <node index="1">
                <host>zookeeper.default.svc.cluster.local</host>
                <port>2181</port>
            </node>
        </zookeeper>
        
        <macros>
            <cluster>company_cluster</cluster>
            <shard>1</shard>
            <replica>clickhouse-$(HOSTNAME)</replica>
        </macros>
        
        <distributed_ddl>
            <path>/clickhouse/task_queue/ddl</path>
            <pool>default</pool>
        </distributed_ddl>
        
        <format_schema_path>/var/lib/clickhouse/format_schemas/</format_schema_path>
    </clickhouse>

  users.xml: |
    <clickhouse>
        <profiles>
            <default>
                <distributed_ddl_entry_format_version>2</distributed_ddl_entry_format_version>
                <max_memory_usage>10000000000</max_memory_usage>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>in_order</load_balancing>
                <log_queries>1</log_queries>
            </default>
        </profiles>

        <users>
            <default>
                <password></password>
                <profile>default</profile>
                <networks>
                    <ip>::/0</ip>
                </networks>
                <quota>default</quota>
            </default>
            <admin>
                <password>123</password>
                <profile>default</profile>
                <networks>
                    <ip>::/0</ip>
                </networks>
                <quota>default</quota>
            </admin>
        </users>

        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>
                    <queries>0</queries>
                    <errors>0</errors>
                    <result_rows>0</result_rows>
                    <read_rows>0</read_rows>
                    <execution_time>0</execution_time>
                </interval>
            </default>
        </quotas>
    </clickhouse>
