apiVersion: v1
kind: ConfigMap
metadata:
  name: etl-env
  namespace: default
data:
  CLICKHOUSE_HOST: "clickhouse-0.clickhouse.default.svc.cluster.local"
  CLICKHOUSE_PORT: "8123"
  KAFKA_HOST: "kafka"
  KAFKA_PORT: "9092"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaffka-etl-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaffka-etl-service
  template:
    metadata:
      labels:
        app: kaffka-etl-service
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command: ['sh', '-c', 'until nc -z kafka 9092; do sleep 1; done;']
        - name: wait-for-clickhouse
          image: busybox
          command: ['sh', '-c', 'until nc -z clickhouse-0.clickhouse.default.svc.cluster.local 8123; do sleep 1; done;']
      containers:
        - name: etl-service
          image: rikhoff/ugc_etl:latest
          envFrom:
            - configMapRef:
                name: etl-env
---