include:
  - 'docker-compose_main.yml'
  - './ugc_service/ugc.yml'
  - './rating_review_api/rating-review.yml'
  - './notifications_api/notifications.yml'
  - './infra/nginx.yml'

services:

  prometheus:
      image: prom/prometheus
      container_name: prometheus
      ports:
        - "9090:9090"
      volumes:
      #  - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
      #  - ./prometheus_data/alert_rules.yml:/etc/prometheus/alert_rules.yml
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      depends_on:
        - redis
        - db
        - app
        - file_api

  grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      volumes:
        - grafana_data:/var/lib/grafana
      depends_on:
        - prometheus
        
  alertmanager:
      image: prom/alertmanager
      container_name: alertmanager
      ports:
        - "9093:9093"
      volumes:
        - ./alertmanager_data/alertmanager.yml:/etc/alertmanager/alertmanager.yml

volumes: