services:

# ---- сервис nginx ----
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./nginx/configs:/etc/nginx/conf.d:z
      - static:/data/static/:z
    depends_on:
      - django_admin
      - auth
      - app
      - file_api
      - rating_review_api
      - notification_api
      - logstash
    ports:
      - "80:80"
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:5044
        tag: nginx