apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
data:
  alert.rules.yml: |
    groups:
      - name: alert_rules
        rules:
          - alert: HighCPUUsage
            expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (instance) > 0.9
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Высокая загрузка CPU на {{ $labels.instance }}"
              description: "Загрузка CPU превышает 90% более 5 минут."
    
          - alert: MemoryUsageHigh
            expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes < 0.2
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Высока нагрузка оперативной памяти от {{ $labels.instance }}"
              description: "Доступный объем оперативной памяти менее 20% на {{ $labels.instance }}."
    
          - alert: LowDiskSpace
            expr: node_filesystem_free_bytes / node_filesystem_size_bytes < 0.1
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Заканчивается место на диске для {{ $labels.instance }}"
              description: "Место на диске менее 10% на {{ $labels.instance }}."