# ConfigMap с конфигурацией Alertmanager
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    route:
      group_by: [ 'alertname' ]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: email-receiver
      routes:
        - match:
            severity: critical
          receiver: telegram-receiver

    receivers:
      - name: email-receiver
        email_configs:
          - to: "${ALERT_EMAIL_TO}"
            from: "${ALERT_EMAIL_FROM}"
            smarthost: "${ALERT_EMAIL_SMARTHOST}"
            auth_username: "${ALERT_EMAIL_USERNAME}"
            auth_password: "${ALERT_EMAIL_PASSWORD}"

      - name: telegram-receiver
        webhook_configs:
          - url: "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage?chat_id=${TELEGRAM_CHAT_ID}"
---
# Deployment для Alertmanager
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.23.0
        args:
          - "--config.file=/etc/alertmanager/alertmanager.yml"
        ports:
          - containerPort: 9093
        volumeMounts:
          - name: config-volume
            mountPath: /etc/alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
---
# Service для Alertmanager
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
spec:
  type: ClusterIP
  selector:
    app: alertmanager
  ports:
    - name: alertmanager
      port: 9093
      targetPort: 9093