FROM python:3.10

WORKDIR /opt/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE 'config.settings'

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip \
    && pip install -r requirements.txt --no-cache

COPY . .

# Создаем непривилегированного пользователя
RUN useradd -m celery_user \
    && chown -R celery_user:celery_user /opt/app

USER celery_user
