apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-container
          image: rikhoff/movies_auth:latest
          command: [ "uvicorn" ]
          args: [ "--app-dir", "./src", "main:app", "--host", "0.0.0.0", "--port", "8080" ]
          envFrom:
            - secretRef:
                name: api-movie-env
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
---

apiVersion: batch/v1
kind: Job
metadata:
  name: migrations-job
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 10000
  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 $DB_HOST $DB_PORT; do echo "Waiting for database..."; sleep 5; done']
          envFrom:
            - secretRef:
                name: api-movie-env
      containers:
      - name: backend-container
        image: rikhoff/movies_auth:latest
        envFrom:
          - secretRef:
              name: api-movie-env
        imagePullPolicy: Never
        args:
        - /bin/sh
        - -c
        - alembic upgrade head
      restartPolicy: Never 
--- 


