apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      containers:
        - name: notification-api
          image: notification_api:latest
          envFrom:
            - configMapRef:
                name: notification-config
          ports:
            - containerPort: 8765
          volumeMounts:
            - name: app-storage
              mountPath: /app
      volumes:
        - name: app-storage
          hostPath:
            path: ./app