# Generated by Django 4.2.11 on 2025-01-10 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                (
                    "type",
                    models.CharField(
                        choices=[("private", "PRIVATE"), ("group", "GROUP")],
                        default="private",
                        verbose_name="type",
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("email", "EMAIL"), ("push", "PUSH")],
                        default="email",
                        verbose_name="delivery_type",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="scheduled_time"
                    ),
                ),
                (
                    "repeat_type",
                    models.CharField(
                        blank=True,
                        default="* * * * *",
                        help_text="Введите интервал повторения в формате: '* * * * *' * - 1 * минута 2 * час 3 * день месяца 4 * месяц 5 * день недели",
                        max_length=50,
                        null=True,
                        verbose_name="repeat_type",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        primary_key=True, serialize=False, verbose_name="slug"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "description",
                    models.CharField(max_length=250, verbose_name="description"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Содержимое уведомления", verbose_name="content"
                    ),
                ),
            ],
            options={
                "verbose_name": "template",
                "verbose_name_plural": "templates",
            },
        ),
        migrations.CreateModel(
            name="NotificationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "send_attempts",
                    models.IntegerField(default=0, verbose_name="Query retries count"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "SENT"),
                            ("attempting", "PENDING"),
                            ("delivered", "DELIVERED"),
                            ("failed", "FAILED"),
                        ],
                        default="attempting",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last update"),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notification",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="groups",
            field=models.ManyToManyField(
                related_name="notifications",
                through="notifications.NotificationGroup",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="notifications.template"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="users",
            field=models.ManyToManyField(
                related_name="notifications",
                through="notifications.NotificationUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
