# Generated by Django 4.2.11 on 2025-01-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="type",
        ),
        migrations.DeleteModel(
            name="NotificationGroup",
        ),
    ]
