apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:  
  filebeat.yml: |
    name: "post-service-filebeat"

    logging.metrics.enabled: false
    xpack.security.enabled: false
    xpack.monitoring.enabled: false

    filebeat.inputs:
      - type: filestream
        scan_frequency: 1s
        enabled: true
        paths:
          - /var/log/nginx/*.log
        json:
          keys_under_root: true
          add_error_key: true

        processors:
          - decode_json_fields:
              fields: ["message"]
              process_array: false
              max_depth: 2
              target: ""
              overwrite_keys: true
              add_error_key: false

    output.logstash:
      enabled: true
      hosts: ["logstash:5045"]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
        - name: filebeat
          image: elastic/filebeat:8.10.2
          volumeMounts:
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: logs
              mountPath: /var/log/nginx
              readOnly: true
          command: ["filebeat", "-e", "-strict.perms=false"]
      volumes:
        - name: filebeat-config
          configMap:
            name: filebeat-config
        - name: logs
          hostPath:
            path: /var/log/nginx
