apiVersion: v1
kind: ConfigMap
metadata:
  name: rating-review-api-env
data:
  DATABASE_URL: "mongodb://mongodb:27017/review_db"
  KAFKA_BROKER: "kafka:9092"
  SENTRY_DSN: "https://55f2f6b47de6a2186dea7a9d3ac17585@o4505551367831552.ingest.us.sentry.io/4508382176870400"
  LOG_LEVEL: "info"
  LOGGING_DRIVER: "gelf"
  GELF_ADDRESS: "udp://logstash:5044"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-review-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-review-api
  template:
    metadata:
      labels:
        app: rating-review-api
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command: ['sh', '-c', 'until nc -z mongodb 27017; do sleep 1; done;']
      containers:
        - name: rating-review-api
          image: rikhoff/movies_rating_review:latest
          envFrom:
            - configMapRef:
                name: rating-review-api-env 
          ports:
            - containerPort: 8766
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8766
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8766
            initialDelaySeconds: 2
            periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: rating-review-api
spec:
  selector:
    app: rating-review-api
  ports:
    - protocol: TCP
      port: 8766
      targetPort: 8766
