---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rating-review-api-env
data:
  DB_HOST: mongodb-service
  DB_PORT: "27017"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-review-api
  labels:
    app: rating-review-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-review-api
  template:
    metadata:
      labels:
        app: rating-review-api
    spec:
      containers:
        - name: rating-review-api
          image: rating-review-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8765
          envFrom:
            - configMapRef:
                name: rating-review-api-env
          readinessProbe:
            httpGet:
              path: /
              port: 8765
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8765
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: rating-review-api-service
spec:
  selector:
    app: rating-review-api
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
  type: ClusterIP
