apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'notification-api'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['notification-api.default.svc.cluster.local:8765']

      - job_name: 'all-services-default'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            regex: default
            action: keep