apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq...; sleep 2; done;']
      containers:
        - name: notification-api
          image: notifications-api:latest
          envFrom:
            - configMapRef:
                name: notification-config
          ports:
            - containerPort: 8765
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: notification-api
spec:
  selector:
    app: notification-api
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
