apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
        - name: sender
          image: notification-sender-worker:latest
          envFrom:
            - configMapRef:
                name: notification-config
          imagePullPolicy: Never