# Generated by Django 4.2.11 on 2025-01-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (""),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_settings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="push_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
